name: Rust

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build CLI Release App
        run: cargo build --release --verbose
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
