name: Rust

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    name: "Build findline for mac apple systems"
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin

    runs-on: macos-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build for ${{ matrix.target }} Release
        run: cargo build --release --target=${{ matrix.target }} --verbose

      - name: Package build artifacts
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/findline dist/findline-${{ matrix.target }}
          tar -czvf dist/findline-${{ matrix.target }}.tar.gz -C dist findline-${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: dist/findline-${{ matrix.target }}.tar.gz

  build-linux:
    name: "Build findline for linux and musl systems"
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build for ${{ matrix.target }} Release
        run: cross build --release --target=${{ matrix.target }} --verbose

      - name: Package build artifacts
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/findline dist/findline-${{ matrix.target }}
          tar -czvf dist/findline-${{ matrix.target }}.tar.gz -C dist findline-${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: dist/findline-${{ matrix.target }}.tar.gz

  release:
    needs: [build-macos, build-linux]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/findline-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
